
sensor:
  - platform: debug
    free:
      name: "Heap Free"
    # fragmentation:
    #   name: "Heap Fragmentation"
    # block:
    #   name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    # psram:
    #   name: "Free PSRAM"
  # Home Assistant remote temperature sensor
  - platform: homeassistant
    name: "Garage AC Remote Temperature Sensor"
    entity_id: sensor.garage_west_env_sensor_temperature
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
      - lambda: return (x - 32.0) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1.0
          max_value: 40.0
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(garage_ac).set_remote_temperature(x);'

  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime
    unit_of_measurement: days
    update_interval: 3600s
    accuracy_decimals: 1
    filters:
      - multiply: 0.000011574
    device_class: duration
    state_class: total_increasing
    entity_category: diagnostic

  - platform: internal_temperature
    name: ${name} Internal ESP temperature
    entity_category: diagnostic

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: Signal dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: Signal %
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
    entity_category: diagnostic
    device_class: ""

text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
      id: wifi_ip  # ID pour référence dans l'écran
    ssid:
      name: ${name} SSID
      id: wifi_ssid  # ID pour référence dans l'écran
    bssid:
      name: ${name} BSSID
      id: wifi_bssid  # ID pour référence dans l'écran

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"